remote_theme: pages-themes/minimal
plugins:
- jekyll-remote-theme
title: Anthony Brown's pages
description: 
  This site links to my teaching demos and other projects that I maintain on Github
github_username: agabrown
